# Generated by Django 3.2.5 on 2021-07-28 08:47

import django.core.validators
from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('done', 'done')], default='pending', editable=False, max_length=10)),
                ('image_filter', models.CharField(choices=[('GaussianNoise', 'GaussianNoise'), ('Rotate', 'Rotate'), ('AddToHueAndSaturation', 'AddToHueAndSaturation')], max_length=30)),
                ('severity', models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rotate', models.SmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(-360), django.core.validators.MaxValueValidator(360)])),
                ('value_hue', models.SmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-255), django.core.validators.MaxValueValidator(255)])),
                ('value_saturation', models.SmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-255), django.core.validators.MaxValueValidator(255)])),
                ('per_channel', models.CharField(blank=True, default='False', max_length=10, null=True)),
                ('file', models.ImageField(upload_to=job.models.image_directory_path)),
            ],
        ),
    ]
